### ISSUE TITLE
Error in uploading morse and utils folder to Pico H

### ISSUE THREAD

**Issue by edelaney11** [gilesknap/pico-xmas#1]
Hi Giles,
Thanks for sharing your code for various functions for the Pi Advent Calendar. I am attempting to follow on, but I am having issues uploading the morse and utils folder to the Pi. Specifically, I am getting an "upload.failed timeout" error. Do you know if there is any fix for this?
Thanks

**Comment by kihonkai** [comment]
@edelaney11, I've just come across this code too (@gilesknap, nice code and thanks for sharing).  I just opened Thonny, connected the USB cable to the PC for the pico then hit the red stop icon the toolbar for Stop/Restart backend which is also in the Run menu and on keyboard shortcut Ctrl+F2.  This is so it shows the normal prompt in the shell like this:

```
MicroPython v1.19.1 on 2022-06-18; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> 
```

Then I could navigate to where I had cloned this Git repo locally in the Files pane, I right clicked the morse & utils folders one by one and used "Upload to /" which worked.

I cannot recall the exact steps but I think I've seen that error before and it seems that stop/restart action helps or maybe even unplugging and plugging in the USB cable on the computer.  Thonny is really good for what it does but has some odd bugs like that still.

**Comment by gilesknap** [comment]
Hi @edelaney11 and @kihonkai thanks for the interest!

I have seen the issue with upload and in fact have reported this against the pico-w-go plugin here https://github.com/paulober/Pico-W-Go/issues/36.

@edelaney11 I'm guessing that you are using vscode and pico-w-go as that is where I have seen the issue. I also tried flattening the structure but I was still getting upload issues so reverted to using the folders. As it turns out that not having folders is more likely to succeed, I'll revert once again to flat structure.

My rather nasty workaround is that when you see the upload pausing at a given file focus on the command line window and hit ctrl-C - this sends a soft reset and moves on to the next file. Assuming you get the timing right this will upload all the files correctly. Once you have done it once things get better as the next upload is incremental and usually does not hang.
BTW - pico-w-go works much better when you realize that it adds these commands to the status bar of vscode
![image](https://user-images.githubusercontent.com/964827/205498807-9e97c9db-4e0a-4cf8-8877-5b22143753fa.png)
I'll drop that in the readme.

Thonny does not seem to have this problem but I didn't find Thonny lent itself to using version control as nicely as vscode with the extension. Plus I get all my usual plugins for python with vscode.

**Comment by kihonkai** [comment]
@gilesknap, I get what you mean on version control in Thonny vs VS Code, I use VS Code for almost everything else at home and work.  I'll have to try out the plugin for the Pico.

**Comment by vifeng** [comment]
> 

hi, 
almost the same issue here : I can't upload the  whole project, "the upload one file only" works but is useless since i need all the files (even in the same folder) of them. I tried to select all file and upload the project, I try to select the folder and upload the project, I tried to upload one by one. No chances.
It's more of an extension issue so I'll copy paste the issue in the other repo.
`
here is my trace FYI: 
---------------- uploading the project -------------------------
>>> 
Uploading project (main folder)...
Not safe booting, disabled in settings

Uploading to / ...
Reading file status
No files to upload
Upload done, resetting board...
OK
>>> Running d01_start_morse.py
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'morse_code'

---------------- uploading one file -------------------------
>>> 
Uploading current file (d01_start_morse.py)...
Not safe booting, disabled in settings

Uploading to / ...
Reading file status
Uploading single file
[1/1] Writing file 'AdventPico/pico-xmas/d01_start_morse.py' (286 bytes)
Upload done, resetting board...
OK
>>> Running d01_start_morse.py
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'morse_code'
 
 `

**Comment by gilesknap** [comment]
Did you try focussing on the terminal and hitting ctrl C when it hangs? Works for me.

**Comment by vifeng** [comment]
I did finally succeeded. I had to upload one single file first, then upload the project and CTL+C like you said. it happens so fast... Anyway it is not easy. the ftp doesn't seems to work either. which would have been nice. thank you a lot giles. I can morse, I can't wait to buzz. tit tit titi titi tit tit

**Comment by gilesknap** [comment]
awaiting fix from https://github.com/paulober/Pico-W-Go/issues/36

**Comment by gilesknap** [comment]
Hey. Got a fix in version 3.0.2! See https://github.com/paulober/Pico-W-Go/issues/36

Closing.
